Modifying configure file for enable to compile with private libraries

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -63,14 +63,19 @@ testlibevent2_comp() {
 }
 
 testhiredis() {
+    if [ -n "${HIREDIS_CFLAGS}" ] && [ -n "${HIREDIS_LIBS}" ]; then
+    	P_DBCFLAGS="${P_DBCFLAGS} ${HIREDIS_CFLAGS}"
+    	P_DBLIBS="${P_DBLIBS} ${HIREDIS_LIBS}"
+    	return 1
+    fi
     for inc in ${INCLUDEDIR}/hiredis /usr/local/include/hiredis /usr/hiredis /usr/include/hiredis
     do
         if [ -d ${inc} ] ; then
-            HIREDISCFLAGS="${HIREDISCFLAGS} -I${inc}"
+            HIREDIS_CFLAGS="${HIREDIS_CFLAGS} -I${inc}"
         fi
     done
-    HIREDISLIBS=-lhiredis
-    ${CC} ${HR_TMPCPROGC} -o ${HR_TMPCPROGB} ${OSCFLAGS} ${DBLIBS} ${HIREDISCFLAGS} ${HIREDISLIBS} ${OSLIBS} 2>>/dev/null
+    HIREDIS_LIBS=-lhiredis
+    ${CC} ${HR_TMPCPROGC} -o ${HR_TMPCPROGB} ${OSCFLAGS} ${DBLIBS} ${HIREDIS_CFLAGS} ${HIREDIS_LIBS} ${OSLIBS} 2>>/dev/null
     ER=$?
     if ! [ ${ER} -eq 0 ] ; then
 		${ECHO_CMD}
@@ -80,27 +85,32 @@ testhiredis() {
 		${ECHO_CMD}
 		return 0
     else
-		DBCFLAGS="${DBCFLAGS} ${HIREDISCFLAGS}"
-		DBLIBS="${DBLIBS} ${HIREDISLIBS}"
+		DBCFLAGS="${DBCFLAGS} ${HIREDIS_CFLAGS}"
+		DBLIBS="${DBLIBS} ${HIREDIS_LIBS}"
 		return 1
     fi
 }
 
 testlibpq() {
-    POSTCFLAGS="-I${PREFIX}/pgsql/include -I${PREFIX}/include/pgsql/ -I${PREFIX}/include/postgres/ -I${PREFIX}/postgres/include/ -I${PREFIX}/include/postgresql/ -I${PREFIX}/postgresql/include/"
-    POSTCFLAGS="${POSTCFLAGS} -I/usr/local/pgsql/include -I/usr/local/include/pgsql/ -I/usr/local/include/postgres/ -I/usr/local/postgres/include/ -I/usr/local/include/postgresql/ -I/usr/local/postgresql/include/"
-    POSTCFLAGS="${POSTCFLAGS} -I/usr/pgsql/include -I/usr/include/pgsql/ -I/usr/include/postgres/ -I/usr/postgres/include/ -I/usr/include/postgresql/ -I/usr/postgresql/include/"
+    if [ -n "${PSQL_CFLAGS}" ] && [ -n "${PSQL_LIBS}" ]; then
+    	P_DBCFLAGS="${P_DBCFLAGS} ${PSQL_CFLAGS}"
+    	P_DBLIBS="${P_DBLIBS} ${PSQL_LIBS}"
+    	return 1
+    fi
+    PSQL_CFLAGS="-I${PREFIX}/pgsql/include -I${PREFIX}/include/pgsql/ -I${PREFIX}/include/postgres/ -I${PREFIX}/postgres/include/ -I${PREFIX}/include/postgresql/ -I${PREFIX}/postgresql/include/"
+    PSQL_CFLAGS="${PSQL_CFLAGS} -I/usr/local/pgsql/include -I/usr/local/include/pgsql/ -I/usr/local/include/postgres/ -I/usr/local/postgres/include/ -I/usr/local/include/postgresql/ -I/usr/local/postgresql/include/"
+    PSQL_CFLAGS="${PSQL_CFLAGS} -I/usr/pgsql/include -I/usr/include/pgsql/ -I/usr/include/postgres/ -I/usr/postgres/include/ -I/usr/include/postgresql/ -I/usr/postgresql/include/"
     for ilib in ${PREFIX}/pgsql/lib ${PREFIX}/lib/pgsql ${PREFIX}/lib64/pgsql /usr/local/pgsql/lib /usr/local/lib/pgsql /usr/local/lib64/pgsql /usr/pgsql/lib /usr/lib/pgsql /usr/lib64/pgsql ${PREFIX}/postgres/lib ${PREFIX}/lib/postgres ${PREFIX}/lib64/postgres /usr/local/postgres/lib /usr/local/lib/postgres /usr/local/lib64/postgres /usr/postgres/lib /usr/lib/postgres /usr/lib64/postgres ${PREFIX}/postgresql/lib ${PREFIX}/lib/postgresql ${PREFIX}/lib64/postgresql /usr/local/postgresql/lib /usr/local/lib/postgresql /usr/local/lib64/postgresql /usr/postgresql/lib /usr/lib/postgresql /usr/lib64/postgresql
     do
 	if [ -d ${ilib} ] ; then
-    	    POSTLIBS="${POSTLIBS} -L${ilib}"
+    	    PSQL_LIBS="${PSQL_LIBS} -L${ilib}"
 	    if ! [ -z "${TURN_ACCEPT_RPATH}" ] ; then
 		TURN_RPATH="${TURN_RPATH} -Wl,-rpath,${ilib}"
 	    fi
 	fi
     done
-    POSTLIBS="${OSLIBS} ${POSTLIBS} -lpq"
-    ${CC} ${PQ_TMPCPROGC} -o ${PQ_TMPCPROGB} ${OSCFLAGS} ${DBCFLAGS} ${POSTCFLAGS} ${DBLIBS} ${POSTLIBS} ${OSLIBS} 2>>/dev/null 
+    PSQL_LIBS="${OSLIBS} ${PSQL_LIBS} -lpq"
+    ${CC} ${PQ_TMPCPROGC} -o ${PQ_TMPCPROGB} ${OSCFLAGS} ${DBCFLAGS} ${PSQL_CFLAGS} ${DBLIBS} ${PSQL_LIBS} ${OSLIBS} 2>>/dev/null 
     ER=$?
     if ! [ ${ER} -eq 0 ] ; then
     	${ECHO_CMD}
@@ -110,13 +120,18 @@ testlibpq() {
 		${ECHO_CMD}
 		return 0
     else
-		DBCFLAGS="${DBCFLAGS} ${POSTCFLAGS}"
-		DBLIBS="${DBLIBS} ${POSTLIBS}"
+		DBCFLAGS="${DBCFLAGS} ${PSQL_CFLAGS}"
+		DBLIBS="${DBLIBS} ${PSQL_LIBS}"
 		return 1
     fi
 }
 
 testlibmysql() {
+    if [ -n "${MYSQL_CFLAGS}" ] && [ -n "${MYSQL_LIBS}" ]; then
+    	P_DBCFLAGS="${P_DBCFLAGS} ${MYSQL_CFLAGS}"
+    	P_DBLIBS="${P_DBLIBS} ${MYSQL_LIBS}"
+    	return 1
+    fi
     MYSQL_CFLAGS="-I${PREFIX}/mysql/include -I${PREFIX}/include/mysql/"
     MYSQL_CFLAGS="${MYSQL_CFLAGS} -I/usr/local/mysql/include -I/usr/local/include/mysql/"
     MYSQL_CFLAGS="${MYSQL_CFLAGS} -I/usr/mysql/include -I/usr/include/mysql/"
@@ -147,6 +162,11 @@ testlibmysql() {
 }
 
 testlibmongoc() {
+    if [ -n "${MONGO_CFLAGS}" ] && [ -n "${MONGO_LIBS}" ]; then
+    	P_DBCFLAGS="${P_DBCFLAGS} ${MONGO_CFLAGS}"
+    	P_DBLIBS="${P_DBLIBS} ${MONGO_LIBS}"
+    	return 1
+    fi
     for inc in ${INCLUDEDIR}/libmongoc-1.0 ${INCLUDEDIR}/libbson-1.0 /usr/local/include/libmongoc-1.0 /usr/local/include/libbson-1.0 /usr/libmongoc-1.0 /usr/libbson-1.0 /usr/include/libbson-1.0/ /usr/include/libmongoc-1.0/
     do
       if [ -d ${inc} ] ; then
@@ -910,28 +930,32 @@ testdaemon
 # Test OpenSSL installation
 ###########################
 
-testlib crypto
-ER=$?
-if ! [ ${ER} -eq 0 ] ; then
-    ${ECHO_CMD} "Crypto SSL lib found."
+if [ -n "${SSL_CFLAGS}" ] && [ -n "${SSL_LIBS}" ]; then
+    P_CFLAGS="${P_CFLAGS} ${SSL_CFLAGS}"
+    P_LDFLAGS="${P_LDFLAGS} ${SSL_LIBS}"
 else
-    ${ECHO_CMD} "ERROR: OpenSSL Crypto development libraries are not installed properly in required location."
-    ${ECHO_CMD} "Abort."
-    cleanup
-    exit
-fi
+    testlib crypto
+    ER=$?
+    if ! [ ${ER} -eq 0 ] ; then
+        ${ECHO_CMD} "Crypto SSL lib found."
+    else
+        ${ECHO_CMD} "ERROR: OpenSSL Crypto development libraries are not installed properly in required location."
+        ${ECHO_CMD} "Abort."
+        cleanup
+        exit
+    fi
 
-testlib ssl
-ER=$?
-if ! [ ${ER} -eq 0 ] ; then
-    ${ECHO_CMD} "SSL lib found."
-else
-    ${ECHO_CMD} "ERROR: OpenSSL development libraries are not installed properly in required location."
-    ${ECHO_CMD} "Abort."
-    cleanup
-    exit
+    testlib ssl
+    ER=$?
+    if ! [ ${ER} -eq 0 ] ; then
+        ${ECHO_CMD} "SSL lib found."
+    else
+        ${ECHO_CMD} "ERROR: OpenSSL development libraries are not installed properly in required location."
+        ${ECHO_CMD} "Abort."
+        cleanup
+        exit
+    fi
 fi
-
 ###########################
 # Can we use GCM cipher ?
 ###########################
@@ -953,71 +977,76 @@ fi
 ###########################
 # Test Libevent2 setup
 ###########################
-testlibevent2_comp
-ER=$?
-if ! [ ${ER} -eq 0 ] ; then
-    ${ECHO_CMD} "Libevent2 development found."
+if [ -n "${EVENT_CFLAGS}" ] && [ -n "${EVENT_LIBS}" ]; then
+    P_CFLAGS="${P_CFLAGS} ${EVENT_CFLAGS}"
+    P_LDFLAGS="${P_LDFLAGS} ${EVENT_LIBS}"
 else
-    ${ECHO_CMD} "ERROR: Libevent2 development libraries are not installed properly in required location."
-    ${ECHO_CMD} "ERROR: may be you have just too old libevent tool - then you have to upgrade it."
-    ${ECHO_CMD} "See the INSTALL file."
-    ${ECHO_CMD} "Abort."
-    cleanup
-    exit
-fi
-
-testlib event_core
-ER=$?
-if ! [ ${ER} -eq 0 ] ; then
-    ${ECHO_CMD} "Libevent2 runtime found."
-    testlib event_extra
+    testlibevent2_comp
     ER=$?
     if ! [ ${ER} -eq 0 ] ; then
-	${ECHO_CMD} "Libevent2 runtime 'extra' found."
+        ${ECHO_CMD} "Libevent2 development found."
     else
-	${ECHO_CMD} "ERROR: Libevent2 'extra' runtime library is not installed properly in required location."
-	${ECHO_CMD} "See the INSTALL file."
-	${ECHO_CMD} "Abort."
-	cleanup
-	exit
+        ${ECHO_CMD} "ERROR: Libevent2 development libraries are not installed properly in required location."
+        ${ECHO_CMD} "ERROR: may be you have just too old libevent tool - then you have to upgrade it."
+        ${ECHO_CMD} "See the INSTALL file."
+        ${ECHO_CMD} "Abort."
+        cleanup
+        exit
     fi
-else
-    testlib event
+
+    testlib event_core
     ER=$?
     if ! [ ${ER} -eq 0 ] ; then
-		${ECHO_CMD} "Libevent2 runtime found (old style)."
+        ${ECHO_CMD} "Libevent2 runtime found."
+        testlib event_extra
+        ER=$?
+        if ! [ ${ER} -eq 0 ] ; then
+	    ${ECHO_CMD} "Libevent2 runtime 'extra' found."
+        else
+	    ${ECHO_CMD} "ERROR: Libevent2 'extra' runtime library is not installed properly in required location."
+	    ${ECHO_CMD} "See the INSTALL file."
+	    ${ECHO_CMD} "Abort."
+	    cleanup
+	    exit
+        fi
     else
-		${ECHO_CMD} "ERROR: Libevent2 runtime libraries are not installed properly in required location."
-		${ECHO_CMD} "See the INSTALL file."
-		${ECHO_CMD} "Abort."
-		cleanup
-		exit
+        testlib event
+        ER=$?
+        if ! [ ${ER} -eq 0 ] ; then
+            ${ECHO_CMD} "Libevent2 runtime found (old style)."
+        else
+            ${ECHO_CMD} "ERROR: Libevent2 runtime libraries are not installed properly in required location."
+            ${ECHO_CMD} "See the INSTALL file."
+            ${ECHO_CMD} "Abort."
+            cleanup
+            exit
+        fi
     fi
-fi
 
-if [ -z "${TURN_NO_TLS}" ] ; then
+    if [ -z "${TURN_NO_TLS}" ] ; then
 
 	testlib event_openssl
 	ER=$?
 	if ! [ ${ER} -eq 0 ] ; then
-    	${ECHO_CMD} "Libevent2 openssl found."
+    	    ${ECHO_CMD} "Libevent2 openssl found."
 	else
-    	${ECHO_CMD} "ERROR: Libevent2 development libraries are not compiled with OpenSSL support."
-    	${ECHO_CMD} "TLS will be disabled."
-    	TURN_NO_TLS="-DTURN_NO_TLS"
+    	    ${ECHO_CMD} "ERROR: Libevent2 development libraries are not compiled with OpenSSL support."
+    	    ${ECHO_CMD} "TLS will be disabled."
+    	    TURN_NO_TLS="-DTURN_NO_TLS"
 	fi
 
-else
+    else
 	TURN_NO_TLS="-DTURN_NO_TLS"
-fi
+    fi
 
-testlib event_pthreads
-ER=$?
-if ! [ ${ER} -eq 0 ] ; then
-	${ECHO_CMD} "Libevent2 pthreads found."
-else
-   	${ECHO_CMD} "ERROR: Libevent2 development libraries are not compiled with threads support."
-	exit
+    testlib event_pthreads
+    ER=$?
+    if ! [ ${ER} -eq 0 ] ; then
+        ${ECHO_CMD} "Libevent2 pthreads found."
+    else
+        ${ECHO_CMD} "ERROR: Libevent2 development libraries are not compiled with threads support."
+        exit
+    fi
 fi
 
 ###########################
@@ -1196,11 +1225,11 @@ ${ECHO_CMD} "# Generated by configure script #" >> Makefile
 ${ECHO_CMD} "#################################" >> Makefile
 ${ECHO_CMD} "ECHO_CMD = ${ECHO_CMD}" >> Makefile
 ${ECHO_CMD} "CC = ${CC}" >> Makefile
-${ECHO_CMD} "LDFLAGS += ${OSLIBS}" >> Makefile
-${ECHO_CMD} "DBLIBS += ${DBLIBS}" >> Makefile
-${ECHO_CMD} "CFLAGS += ${OSCFLAGS}" >> Makefile
+${ECHO_CMD} "LDFLAGS += ${P_LDFLAGS} ${OSLIBS}" >> Makefile
+${ECHO_CMD} "DBLIBS += ${P_DBLIBS} ${DBLIBS}" >> Makefile
+${ECHO_CMD} "CFLAGS += ${P_CFLAGS} ${OSCFLAGS}" >> Makefile
 ${ECHO_CMD} "CPPFLAGS = ${CPPFLAGS}" >> Makefile
-${ECHO_CMD} "DBCFLAGS += ${DBCFLAGS} ${TURN_NO_PQ} ${TURN_NO_MYSQL} ${TURN_NO_SQLITE} ${TURN_NO_MONGO} ${TURN_NO_HIREDIS}" >> Makefile
+${ECHO_CMD} "DBCFLAGS += ${P_DBCFLAGS} ${DBCFLAGS} ${TURN_NO_PQ} ${TURN_NO_MYSQL} ${TURN_NO_SQLITE} ${TURN_NO_MONGO} ${TURN_NO_HIREDIS}" >> Makefile
 ${ECHO_CMD} "#" >> Makefile
 ${ECHO_CMD} "PORTNAME = ${PORTNAME}" >> Makefile
 ${ECHO_CMD} "PREFIX = ${PREFIX}" >> Makefile
